# Generated by Django 4.2.30 on 2026-04-24 01:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBlok',
            fields=[
                ('blok', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_blok', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_kepala', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Data harus terdiri dari tepat 16 digit angka.', regex='^\\d{16}$')])),
                ('nama_kepala', models.CharField(blank=True, max_length=100, null=True)),
                ('nik_pasangan', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Data harus terdiri dari tepat 16 digit angka.', regex='^\\d{16}$')])),
                ('nama_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('belum_kawin', 'Belum Kawin'), ('kawin', 'Kawin')], default='belum_kawin', max_length=100)),
                ('jumlah_penghuni', models.IntegerField(blank=True, null=True)),
                ('kartu_keluarga', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Data harus terdiri dari tepat 16 digit angka.', regex='^\\d{16}$')])),
                ('asal_daerah', models.TextField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='ID')),
                ('blok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaroapp.listblok')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
