# Generated by Django 4.2.30 on 2026-04-25 10:00

import avaroapp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('jenis', models.CharField(choices=[('debit', 'Debit'), ('Kredit', 'Kredit')], max_length=10)),
                ('kategori', models.CharField(max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('bukti_transaksi', models.ImageField(blank=True, null=True, upload_to=avaroapp.models.rename_bukti_transaksi)),
                ('user_input', models.DateField(max_length=100)),
                ('warga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avaroapp.profile')),
            ],
        ),
    ]
