# Generated by Django 4.2.30 on 2026-04-25 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaroapp', '0003_alter_transaksi_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='user_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_dicatat', to=settings.AUTH_USER_MODEL),
        ),
    ]
