# Generated by Django 4.2.30 on 2026-04-25 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0004_alter_transaksi_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='tanggal_input',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
