# Generated by Django 4.2.30 on 2026-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0005_transaksi_tanggal_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='jenis',
            field=models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], max_length=10),
        ),
    ]
