# Generated by Django 4.2.30 on 2026-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0006_alter_transaksi_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_rumah',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
