# Generated by Django 4.2.30 on 2026-05-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0007_profile_no_rumah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='kategori',
        ),
    ]
